name: Build and Publish react-super-ui

on:
  # pull_request:
  #   types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Fetch Base and Head Branches
        run: |
          git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}
          git fetch origin ${GITHUB_HEAD_REF}:${GITHUB_HEAD_REF}
      - name: checkout base branch
        run: git checkout ${GITHUB_HEAD_REF}

      - name: Setup git user
        run: |
          git config user.email "youssouf.kacemi@gmail.com"
          git config user.name "github-actions[bot]"

      - name: Install dependencies
        run: yarn install

      - name: Run Custom Script for PRs
        run: node deploy/test.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_TEST }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_TEST }}

      # - name: Install dependencies
      #   run: yarn install
