name: Build and Publish

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.UI_RELEASE_MERGE_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: git config
        run: |
          git config user.name github-actions[bot]
          git config user.email youssouf.kacemi@gmail.com

      - name: Install dependencies
        run: yarn install

      - name: Run Custom Script for PRs
        if: github.event_name == 'pull_request'
        run: node scripts/release-preview.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token_test }}

      - name: Release with release-it for Master Branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: node scripts/release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token_test }}
          NPM_TOKEN: ${{ secrets.npm_token_test }}
      - name: Install dependencies
        run: yarn install
